# Generated by Django 6.0.6 on 2026-06-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag_alter_post_content_alter_post_slug_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
