# Generated by Django 6.0.6 on 2026-07-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_src',
            new_name='image',
        ),
    ]
