# Generated by Django 6.0.6 on 2026-07-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_image_src_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
