# Generated by Django 6.0.6 on 2026-07-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_author_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
