# Generated by Django 6.0.6 on 2026-07-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='username',
        ),
    ]
