# Generated by Django 6.0.6 on 2026-07-12 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_author_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='email_address',
            new_name='email',
        ),
    ]
